logicalvector<-rep(c(T,F),10)
logicalvector
array1<-array(logicalvector,dim=c(2,2,5))
array1
array1[,,2]
arraya<-array(a,dim=c(3,3,40))
arraya<-(,,20)
getwd()
name<-c("kelvin","kiplagat","vincent","kamau")
name
age<-c(1,2,90,101)
age
regno<-c("acs1","acs2","acs3","acs4")
regno
dataframe8<-data.frame(name,age,regno)
dataframe8
dataframe8$name
mean(dataframe8$age)
age2<-dataframe8$age
age2
x<-dataframe8$age[age==2]
x
date<-rep(1,4,1)
date<-1:4
date<-c(1,2,3,4)
dataframe8$date<-date
dataframe8<-dataframe8$age[age=9]
dataframe8
