# Annual Rainfall in Los Angeles
library(TSA)
data(larain)
plot(larain, ylab = "Inches", xlab = "Year", type = 'o')

# Monthly oil filter sales
data("oilfilters");
plot(oilfilters, type = 'l', ylab ='Sales', lty = 2)
points(y = oilfilters, x = time(oilfilters),
    pch = as.vector(season(oilfilters)))

# U.S Electricity Generated by Month
data(electricity); plot(electricity)
 
# Monthly Price of Oil: January 1986 - January 2006
data(oil.price)
plot(oil.price, ylab = 'Price per barrel', type = 'l')

# A gausian white noise with mu = 0, var = 1
set.seed(1) # make the random result reproducible
et = rnorm(200)
plot(et, type = 'l')

# sample acf
acf(et, main = 'ACF of the data')

# Moving Average model
ma2 <- filter(et, filter = rep(1/2, 2), method = 'convolution')
ma10 <- filter(et, filter = rep(1/10, 2), method = 'convolution')
plot(et, type = 'l')
lines(ma2, col = 2); lines(ma10, col = 3)
legend('topright', legend = c('white noise', 'MA(2)', 'MA(10)'),
      col = 1:3, lty = rep(1,3))

# sample acf
par(mfrow = c(1,2))
acf(ma2, na.action = na.omit); 
acf(ma10, na.action = na.omit)

# Autoregressive process
set.seed(2)
ar1 = arima.sim(n = 100, model = list(ar = c(0.9)))
ar2 = arima.sim(n = 100, model = list(ar = c(-0.9)))
plot(ar1) # ar1 is an object of 'ts' class
lines(ar2, col = 2, lty = 2)
legend('bottomleft', legend = c('AR(1) 0.9', 'AR(1) -0.9'), col = 1:2, lty = 1:2)

# sample acf
par(mfrow = c(1, 2))
acf(ar1); acf(ar2)

# PACF for AR and MA processes
par(mfrow = c(1, 2))
pacf(ar1, main = 'AR(1) 0.9'); pacf(ar2, main = 'AR(1) - 0.9')

par(mfrow = c(1, 2)); set.seed(1)
ar3 = arima.sim(n = 100, model = list(ar = c(0.9, -0.2)))
ar4 = arima.sim(n = 100, model = list(ar = c(0.5, 0.6, -0.7)))
pacf(ar3, main = 'AR(2) (0.9, -0.2)'); pacf(ar4, main = 'AR(3) (0.5, 0.6, -0.7)')

par(mfrow = c(1, 2))
pacf(ma2, na.action = na.omit, main = 'MA(2)')
pacf(ma10, na.action = na.omit, main = 'MA(10)')

# Autoregresive moving average (ARMA) Model
set.seed(1);
arma1 = arima.sim(n = 100, model = list(ar = 0.9, ma = 0.5))
arma2 = arima.sim(n = 100, model = list(ar = 0.9, ma = -0.5))
plot(arma1)
lines(arma2, col = 2, lty = 2)
legend('topright', legend = c('ARMA(1,1) (0.9, 0.5)', 'ARMA(1,1) (0.9, -0.5)'), col = 
         1:2, lty = 1:2)

# GaRCH/ARCH Models
data(CREF); plot(CREF, main = 'Daily price of the fund')
r_t <- CREF[-501]/CREF[-1]
plot.ts(r_t)

# log-returns
plot.ts(log(r_t))

par(mfrow = c(1, 2), pty = 's')
acf(r_t); pacf(r_t)

rt2 <- log(r_t)^2
par(mfrow = c(1, 2), pty = 's')
acf(rt2); pacf(rt2)

# A simulated example
set.seed(1)
garch11.sim=garch.sim(alpha = c(0.2, 0.2), beta = .5, n = 500)
plot(garch11.sim, type = 'l', ylab=expression(r[t]), xlab = 't')

par(mfrow = c(1, 2))
acf(garch11.sim); pacf(garch11.sim)

par(mfrow = c(1, 2))
garch11.sim2 <- garch11.sim^2
acf(garch11.sim2); pacf(garch11.sim2)

# Fit the simulated data
library(tseries)   # for the garch function
g1 <- garch(garch11.sim, order = c(1, 1))
plot(g1)
summary(g1)

par(mfrow = c(1, 2))
acf(residuals(g1)^2, na.action = na.omit); pacf(residuals(g1)^2, na.action = na.omit)

# Fit the CREF fund return data
library(fGarch)
r.cref=diff(log(CREF))*100
m1 = garchFit(~garch(1,1), r.cref)
summary(m1)

par(mfrow = c(1, 2))
plot(m1, which = c(2:5))

predict(m1, n.ahead = 20, plot = T)
